---
- name:     Installeren dependecies
  yum:      name={{ item }}
            state=present
  with_items:
   - bzip2-devel
   - freetype-devel
   - libjpeg-devel
   - libpng-devel
   - libtiff-devel
   - giflib-devel
   - zlib-devel
   - ghostscript-devel
   - djvulibre-devel
   - libwmf-devel
   - jasper-devel
   - libtool-ltdl-devel
   - libX11-devel
   - libXext-devel
   - libXt-devel
   - lcms-devel
   - libxml2-devel
   - librsvg2-devel
   - OpenEXR-devel

- name:     Downloaden ImageMagick
  get_url:  url=https://data.jcid.nl/server/ImageMagick-6.9.5-9.tar.gz
            dest=/opt/ImageMagick.tar.gz

- name:     Uitpakken ImageMagick
  shell:    tar xf /opt/ImageMagick.tar.gz -C /opt && mv /opt/ImageMagick-*/ /opt/ImageMagick/
            creates=/opt/ImageMagick/

- name:     Installeren ImageMagick
  shell:    ./configure && make && make install
            chdir=/opt/ImageMagick/
            creates=/usr/local/bin/convert

- name:     Installeren imagick pecl extensie
  shell:    yes '' |  pecl install imagick-beta
            creates=/usr/lib64/php/modules/imagick.so

- name:     Aanmaken / inladen exenstie
  copy:     src=./imagick.ini
            dest=/etc/php.d/imagick.ini

- name:     Opruimen van imagick
  shell:    rm -rf /opt/ImageMagick/ /opt/ImageMagick.tar.gz
